In [34]:
import numpy as np
import pandas as pd
import scipy as sp
from scipy import stats

from matplotlib import pyplot as plt
import seaborn as sns
sns.set()

%precision 3
%matplotlib inline
pd.set_option("display.max_rows", 10000)

In [35]:
fish_5 = np.array([2,3,4,5,6])

In [36]:
print(np.random.choice(fish_5, size=1, replace=False))
print(np.random.choice(fish_5, size=3, replace=False))

[2]
[4 5 3]


In [37]:
np.random.seed(1)
np.random.choice(fish_5, size=3, replace=False)

array([4, 3, 6])

In [38]:
np.random.seed(1)
sp.mean(np.random.choice(fish_5, size=3, replace=False))

4.333333333333333

In [40]:
fish_100000 = pd.read_csv("sample\\3-4-1-fish_length_100000.csv")["length"]# シリーズ形式で取得
fish_100000.head(5)

0    5.297442
1    3.505566
2    3.572546
3    3.135979
4    4.689275
Name: length, dtype: float64

In [41]:
len(fish_100000)

100000

In [46]:
sampling_result = np.random.choice(fish_100000, size=10, replace=False)
sampling_result

array([5.548, 4.021, 2.637, 2.413, 3.495, 3.695, 4.38 , 3.964, 3.077,
       3.494])

In [47]:
sp.mean(sampling_result)

3.67226682361824